-- Orchestrator Agent Log Table
-- Audit trail of all agent actions (Orchestrator, Worker, Evaluator, Critic)
-- Part of the LLM Orchestration Framework

CREATE TABLE IF NOT EXISTS app.orchestrator_agent_log (
  id uuid DEFAULT gen_random_uuid(),
  session_id uuid) ON DELETE CASCADE,

  -- Agent info
  agent_role varchar(50), -- 'authenticator', 'orchestrator', 'worker', 'evaluator', 'critic'
  agent_action varchar(100), -- e.g., 'intent_detection', 'mcp_call', 'validation', 'quality_check'

  -- Context
  node_context varchar(100), -- Which graph node this action relates to

  -- Input/Output
  input_data jsonb, -- Input to the agent
  output_data jsonb, -- Agent's output

  -- LLM details (if applicable)
  model_used varchar(100),
  tokens_used integer,
  cost_cents integer,

  -- MCP tool call (if applicable)
  mcp_tool_name varchar(100),
  mcp_tool_args jsonb,
  mcp_tool_result jsonb,
  mcp_success boolean,

  -- Result
  success boolean DEFAULT true,
  error_message text,

  -- Natural language output (for user)
  natural_response text, -- User-facing message generated by this agent action

  -- Timing
  duration_ms integer,
  created_ts timestamptz DEFAULT now()
);


-- Comments
COMMENT ON TABLE app.orchestrator_agent_log IS 'Audit trail of all multi-agent orchestrator actions';
COMMENT ON COLUMN app.orchestrator_agent_log.agent_role IS 'Which agent performed this action (authenticator, orchestrator, worker, evaluator, critic)';
COMMENT ON COLUMN app.orchestrator_agent_log.natural_response IS 'User-facing message generated by this agent action';
