apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pmo-app.fullname" . }}-config
  labels:
    {{- include "pmo-app.labels" . | nindent 4 }}
data:
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: {{ .Values.api.port | quote }}
  NODE_ENV: {{ .Values.api.env.NODE_ENV | quote }}
  LOG_LEVEL: {{ .Values.api.env.LOG_LEVEL | quote }}
  
  # Database
  DATABASE_URL: {{ .Values.api.env.DATABASE_URL | quote }}
  
  # Redis
  REDIS_URL: {{ .Values.api.env.REDIS_URL | quote }}
  
  # S3/MinIO
  S3_ENDPOINT: {{ .Values.api.env.S3_ENDPOINT | quote }}
  S3_REGION: {{ .Values.api.env.S3_REGION | quote }}
  S3_BUCKET: {{ .Values.api.env.S3_BUCKET | quote }}
  
  # Email/SMTP
  SMTP_HOST: {{ .Values.api.env.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.api.env.SMTP_PORT | quote }}
  
  # CORS
  WEB_ORIGIN: {{ .Values.api.env.WEB_ORIGIN | quote }}
  API_ORIGIN: {{ .Values.api.env.API_ORIGIN | quote }}
  
  # OpenTelemetry
  OTEL_SERVICE_NAME: "pmo-api"