apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pmo-app.fullname" . }}-secret
  labels:
    {{- include "pmo-app.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT Secret (base64 encoded)
  JWT_SECRET: {{ default "your-super-secret-jwt-key-here" .Values.api.env.JWT_DEV_SECRET | b64enc | quote }}
  
  # S3/MinIO credentials
  S3_ACCESS_KEY: {{ default "minio" .Values.minio.auth.rootUser | b64enc | quote }}
  S3_SECRET_KEY: {{ default "minio123" .Values.minio.auth.rootPassword | b64enc | quote }}
  
  # SMTP credentials (if needed)
  SMTP_USER: {{ default "" .Values.api.env.SMTP_USER | b64enc | quote }}
  SMTP_PASS: {{ default "" .Values.api.env.SMTP_PASS | b64enc | quote }}
  SMTP_FROM: {{ default "noreply@pmo.local" .Values.api.env.SMTP_FROM | b64enc | quote }}
  
  # Development bypass
  {{- if .Values.api.env.DEV_BYPASS_OIDC }}
  DEV_BYPASS_OIDC: {{ .Values.api.env.DEV_BYPASS_OIDC | b64enc | quote }}
  {{- end }}