apiVersion: v1
kind: Service
metadata:
  name: {{ include "pmo-app.fullname" . }}-api
  labels:
    {{- include "pmo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pmo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pmo-app.fullname" . }}-web
  labels:
    {{- include "pmo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pmo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web