import React from 'react';
import { SETTINGS_REGISTRY, createSettingsEntityConfig, applySettingsBadgeRenderers } from './settingsConfig';
// ============================================================================
// Helper Functions for Column Renderers
// ============================================================================
import { formatRelativeTime, formatFriendlyDate } from './frontEndFormatterService';
import { formatLocalizedDate } from './utils/dateUtils';
export const formatDate = (dateString) => {
    return formatLocalizedDate(dateString, 'en-CA', '-');
};
// Centralized date/timestamp renderers
export const renderTimestamp = (value) => {
    return formatRelativeTime(value);
};
export const renderDate = (value) => {
    return formatFriendlyDate(value);
};
export const formatCurrency = (amount, currency = 'CAD') => {
    if (!amount)
        return '-';
    return new Intl.NumberFormat('en-CA', {
        style: 'currency',
        currency
    }).format(amount);
};
export const renderBadge = (value, colorMap) => {
    const colorClass = colorMap[value] || 'bg-dark-100 text-dark-600';
    return React.createElement('span', { className: `inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${colorClass}` }, value);
};
// renderColorBadge is now imported from settingsConfig.ts
/**
 * Render employee names from array
 * Backend API returns employee names in assignee_employee_names field
 */
export const renderEmployeeNames = (names, record) => {
    // Try to use assignee_employee_names from the record first (populated by backend)
    const employeeNames = record?.assignee_employee_names || names;
    if (!employeeNames)
        return React.createElement('span', { className: 'text-dark-600' }, '-');
    // Handle both array and JSON string formats
    let namesArray = [];
    if (typeof employeeNames === 'string') {
        try {
            namesArray = JSON.parse(employeeNames);
        }
        catch {
            namesArray = [employeeNames];
        }
    }
    else if (Array.isArray(employeeNames)) {
        namesArray = employeeNames;
    }
    if (namesArray.length === 0)
        return React.createElement('span', { className: 'text-dark-600' }, '-');
    return React.createElement('div', { className: 'flex flex-wrap gap-1' }, ...namesArray.slice(0, 2).map((name, index) => React.createElement('span', {
        key: index,
        className: 'inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-indigo-100 text-indigo-800'
    }, name)), namesArray.length > 2 ? React.createElement('span', { className: 'text-xs text-dark-700' }, `+${namesArray.length - 2} more`) : null);
};
// ============================================================================
// ALL FIELD DETECTION IS NOW IN frontEndFormatterService.ts
// ============================================================================
/**
 * Field categorization, width assignment, alignment, and rendering logic
 * are now handled by frontEndFormatterService.detectField().
 *
 * See: apps/web/src/lib/frontEndFormatterService.ts
 */
// ============================================================================
// Entity Configurations
// ============================================================================
export const entityConfigs = {
    // --------------------------------------------------------------------------
    // PROJECT
    // --------------------------------------------------------------------------
    project: {
        name: 'project',
        displayName: 'Project',
        pluralName: 'Projects',
        apiEndpoint: '/api/v1/project',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // TASK
    // --------------------------------------------------------------------------
    task: {
        name: 'task',
        displayName: 'Task',
        pluralName: 'Tasks',
        apiEndpoint: '/api/v1/task',
        shareable: true,
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'kanban'],
        defaultView: 'table',
        kanban: {
            groupByField: 'dl__task_stage',
            metaTable: 'dl__task_stage',
            cardFields: ['name', 'dl__task_priority', 'estimated_hours', 'assignee_employee_ids']
        }
    },
    // --------------------------------------------------------------------------
    // WIKI
    // --------------------------------------------------------------------------
    wiki: {
        name: 'wiki',
        displayName: 'Wiki',
        pluralName: 'Wiki Pages',
        apiEndpoint: '/api/v1/wiki',
        shareable: true,
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // ARTIFACT
    // --------------------------------------------------------------------------
    artifact: {
        name: 'artifact',
        displayName: 'Artifact',
        pluralName: 'Artifacts',
        apiEndpoint: '/api/v1/artifact',
        shareable: true,
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // FORM
    // --------------------------------------------------------------------------
    form: {
        name: 'form',
        displayName: 'Form',
        pluralName: 'Forms',
        apiEndpoint: '/api/v1/form',
        shareable: true,
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // BUSINESS (Operational Teams Only)
    // --------------------------------------------------------------------------
    // NOTE: Business hierarchy management is separate (d_business_hierarchy table)
    // This config is for operational business units (teams doing actual work)
    business: {
        name: 'business',
        displayName: 'Business Unit',
        pluralName: 'Business Units',
        apiEndpoint: '/api/v1/business',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // OFFICE (Physical Locations Only)
    // --------------------------------------------------------------------------
    // NOTE: Office hierarchy management is separate (d_office_hierarchy table)
    // This config is for operational office locations (addresses, contacts, etc.)
    office: {
        name: 'office',
        displayName: 'Office',
        pluralName: 'Offices',
        apiEndpoint: '/api/v1/office',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // EMPLOYEE
    // --------------------------------------------------------------------------
    employee: {
        name: 'employee',
        displayName: 'Employee',
        pluralName: 'Employees',
        apiEndpoint: '/api/v1/employee',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // ROLE
    // --------------------------------------------------------------------------
    role: {
        name: 'role',
        displayName: 'Role',
        pluralName: 'Roles',
        apiEndpoint: '/api/v1/role',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // RBAC (Permissions)
    // --------------------------------------------------------------------------
    rbac: {
        name: 'rbac',
        displayName: 'Permission',
        pluralName: 'Permissions',
        apiEndpoint: '/api/v1/rbac',
        columns: [], // Auto-generated from API schema (v4.0)
        // NOTE: RBAC fields use basic types for now. Future enhancement: add autocomplete support
        // See /api/v1/entity/codes for entity types, /api/v1/entity/{type}/options for instances
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // WORKSITE
    // --------------------------------------------------------------------------
    worksite: {
        name: 'worksite',
        displayName: 'Worksite',
        pluralName: 'Worksites',
        apiEndpoint: '/api/v1/worksite',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'grid'],
        defaultView: 'table',
        grid: {
            cardFields: ['name', 'descr']
        }
    },
    // --------------------------------------------------------------------------
    // CUSTOMER
    // --------------------------------------------------------------------------
    cust: {
        name: 'cust',
        displayName: 'Customer',
        pluralName: 'Customers',
        apiEndpoint: '/api/v1/cust',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // SETTINGS ENTITIES (DRY - Generated from Registry)
    // --------------------------------------------------------------------------
    // All settings entities use the factory pattern from settingsConfig.ts
    // This eliminates ~600 lines of repetitive code
    // Project Stage
    projectStage: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'projectStage'))
    },
    // Project Status
    projectStatus: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'projectStatus'))
    },
    // Task Stage
    taskStage: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'taskStage'))
    },
    // Task Priority
    taskPriority: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'taskPriority'))
    },
    // Business Level
    businessLevel: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'businessLevel'))
    },
    // Office Level
    orgLevel: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'orgLevel'))
    },
    // HR Level
    hrLevel: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'hrLevel'))
    },
    // Client Level
    clientLevel: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'clientLevel'))
    },
    // Position Level
    positionLevel: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'positionLevel'))
    },
    // Opportunity Funnel Stage
    opportunityFunnelLevel: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'opportunityFunnelLevel'))
    },
    // Industry Sector
    industrySector: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'industrySector'))
    },
    // Acquisition Channel
    acquisitionChannel: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'acquisitionChannel'))
    },
    // Customer Tier
    customerTier: {
        ...createSettingsEntityConfig(SETTINGS_REGISTRY.find(s => s.key === 'customerTier'))
    },
    // --------------------------------------------------------------------------
    // INVENTORY
    // --------------------------------------------------------------------------
    inventory: {
        name: 'inventory',
        displayName: 'Inventory',
        pluralName: 'Inventory',
        apiEndpoint: '/api/v1/inventory',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // ORDER
    // --------------------------------------------------------------------------
    order: {
        name: 'order',
        displayName: 'Order',
        pluralName: 'Orders',
        apiEndpoint: '/api/v1/order',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // SHIPMENT
    // --------------------------------------------------------------------------
    shipment: {
        name: 'shipment',
        displayName: 'Shipment',
        pluralName: 'Shipments',
        apiEndpoint: '/api/v1/shipment',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // INVOICE
    // --------------------------------------------------------------------------
    invoice: {
        name: 'invoice',
        displayName: 'Invoice',
        pluralName: 'Invoices',
        apiEndpoint: '/api/v1/invoice',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // MARKETING (Email Templates)
    // --------------------------------------------------------------------------
    marketing: {
        name: 'marketing',
        displayName: 'Email Template',
        pluralName: 'Email Templates',
        apiEndpoint: '/api/v1/email-template',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'grid'],
        defaultView: 'table',
        grid: {
            cardFields: ['name', 'subject', 'status', 'updated_ts']
        }
    },
    // WORKFLOW AUTOMATION - REMOVED (not a user-facing entity)
    expense: {
        name: 'expense',
        displayName: 'Expense',
        pluralName: 'Expenses',
        apiEndpoint: '/api/v1/expense',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // REVENUE
    // --------------------------------------------------------------------------
    revenue: {
        name: 'revenue',
        displayName: 'Revenue',
        pluralName: 'Revenue',
        apiEndpoint: '/api/v1/revenue',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // SERVICE
    // --------------------------------------------------------------------------
    service: {
        name: 'service',
        displayName: 'Service',
        pluralName: 'Services',
        apiEndpoint: '/api/v1/service',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // PRODUCT
    // --------------------------------------------------------------------------
    product: {
        name: 'product',
        displayName: 'Product',
        pluralName: 'Products',
        apiEndpoint: '/api/v1/product',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // QUOTE
    // --------------------------------------------------------------------------
    quote: {
        name: 'quote',
        displayName: 'Quote',
        pluralName: 'Quotes',
        apiEndpoint: '/api/v1/quote',
        shareable: true,
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'kanban'],
        defaultView: 'table',
        kanban: {
            groupByField: 'dl__quote_stage',
            metaTable: 'dl__quote_stage',
            cardFields: ['name', 'quote_total_amt', 'customer_name', 'valid_until_date']
        }
    },
    // --------------------------------------------------------------------------
    // WORK ORDER
    // --------------------------------------------------------------------------
    work_order: {
        name: 'work_order',
        displayName: 'Work Order',
        pluralName: 'Work Orders',
        apiEndpoint: '/api/v1/work_order',
        shareable: true,
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'kanban'],
        defaultView: 'table',
        kanban: {
            groupByField: 'dl__work_order_status',
            metaTable: 'dl__work_order_status',
            cardFields: ['name', 'scheduled_date', 'assigned_technician_ids', 'total_cost_amt', 'customer_name']
        }
    },
    // --------------------------------------------------------------------------
    // WORKFLOW
    // --------------------------------------------------------------------------
    workflow: {
        name: 'workflow',
        displayName: 'Workflow',
        pluralName: 'Workflows',
        apiEndpoint: '/api/v1/workflow',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table',
        // Use workflow_instance_id for detail page navigation instead of id
        detailPageIdField: 'workflow_instance_id'
    },
    // --------------------------------------------------------------------------
    // EVENT (Meetings, Appointments, Trainings, Consultations)
    // --------------------------------------------------------------------------
    event: {
        name: 'event',
        displayName: 'Event',
        pluralName: 'Events',
        apiEndpoint: '/api/v1/event',
        shareable: true,
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'calendar'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // PERSON CALENDAR (Universal Availability/Booking Calendar)
    // --------------------------------------------------------------------------
    person_calendar: {
        name: 'person_calendar',
        displayName: 'Calendar Slot',
        pluralName: 'Calendar',
        apiEndpoint: '/api/v1/person-calendar',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'kanban', 'calendar'],
        defaultView: 'table',
        kanbanConfig: {
            groupByField: 'availability_flag',
            titleField: 'title',
            subtitleField: 'from_ts'
        },
        calendarConfig: {
            dateField: 'from_ts',
            endDateField: 'to_ts',
            titleField: 'title',
            personField: 'person_entity_id',
            personTypeField: 'person_entity_type',
            statusField: 'availability_flag'
        }
    },
    // --------------------------------------------------------------------------
    // INTERACTION (Customer Interactions)
    // --------------------------------------------------------------------------
    interaction: {
        name: 'interaction',
        displayName: 'Interaction',
        pluralName: 'Interactions',
        apiEndpoint: '/api/v1/interaction',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // CALENDAR
    // --------------------------------------------------------------------------
    calendar: {
        name: 'calendar',
        displayName: 'Calendar',
        pluralName: 'Calendars',
        apiEndpoint: '/api/v1/person-calendar',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'calendar'],
        defaultView: 'calendar'
    },
    // --------------------------------------------------------------------------
    // CHAT (AI Chat Widget)
    // --------------------------------------------------------------------------
    chat: {
        name: 'chat',
        displayName: 'AI Chat',
        pluralName: 'AI Chat',
        apiEndpoint: '/api/v1/chat',
        columns: [],
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // MESSAGE SCHEMA (Email/SMS/Push Templates)
    // --------------------------------------------------------------------------
    // --------------------------------------------------------------------------
    // MESSAGE_SCHEMA: REMOVED - Template storage, not user-facing entity
    // Message templates stored in d_message_schema, managed via internal APIs only
    // --------------------------------------------------------------------------
    // --------------------------------------------------------------------------
    // MESSAGE (Sent/Scheduled Messages via f_message_data)
    // --------------------------------------------------------------------------
    message: {
        name: 'message',
        displayName: 'Message',
        pluralName: 'Messages',
        apiEndpoint: '/api/v1/message-data',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // OFFICE HIERARCHY (Organizational Structure)
    // --------------------------------------------------------------------------
    office_hierarchy: {
        name: 'office_hierarchy',
        displayName: 'Office Hierarchy',
        pluralName: 'Office Hierarchies',
        apiEndpoint: '/api/v1/office-hierarchy',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'graph'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // BUSINESS HIERARCHY (Organizational Structure)
    // --------------------------------------------------------------------------
    business_hierarchy: {
        name: 'business_hierarchy',
        displayName: 'Business Hierarchy',
        pluralName: 'Business Hierarchies',
        apiEndpoint: '/api/v1/business-hierarchy',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'graph'],
        defaultView: 'table'
    },
    // --------------------------------------------------------------------------
    // PRODUCT HIERARCHY (Product Categorization)
    // --------------------------------------------------------------------------
    product_hierarchy: {
        name: 'product_hierarchy',
        displayName: 'Product Hierarchy',
        pluralName: 'Product Hierarchies',
        apiEndpoint: '/api/v1/product-hierarchy',
        columns: [], // Auto-generated (v4.0)
        // v4.0: Fields auto-generated by EntityInstanceFormContainer via frontEndFormatterService
        fields: [],
        supportedViews: ['table', 'graph'],
        defaultView: 'table'
    }
};
// ============================================================================
// AUTO-APPLY SETTINGS BADGE RENDERERS (DRY Enhancement)
// ============================================================================
/**
 * Automatically apply badge renderers to all datalabel columns
 * This eliminates the need to manually specify render functions for settings fields
 *
 * BEFORE (Manual):
 * { key: 'project_stage', lookupSourceTable: 'datalabel', render: renderSettingBadge('project_stage') }
 *
 * AFTER (Automatic):
 * { key: 'project_stage', lookupSourceTable: 'datalabel' }  // ← render added automatically!
 */
Object.keys(entityConfigs).forEach(entityKey => {
    const config = entityConfigs[entityKey];
    if (config.columns) {
        config.columns = applySettingsBadgeRenderers(config.columns);
    }
});
// ============================================================================
// Helper Functions
// ============================================================================
/**
 * Get entity configuration by name
 */
export function getEntityConfig(entityName) {
    return entityConfigs[entityName];
}
/**
 * Get all entity names
 */
export function getAllEntityNames() {
    return Object.keys(entityConfigs);
}
/**
 * Check if entity supports a specific view
 */
export function supportsView(entityName, view) {
    const config = getEntityConfig(entityName);
    return config ? config.supportedViews.includes(view) : false;
}
/**
 * Get default view for entity
 */
export function getDefaultView(entityName) {
    const config = getEntityConfig(entityName);
    return config?.defaultView || 'table';
}
/**
 * Get all shareable entity names
 * Returns: ['task', 'artifact', 'wiki', 'form']
 */
export function getShareableEntities() {
    return Object.keys(entityConfigs).filter(name => entityConfigs[name].shareable === true);
}
/**
 * Check if entity supports sharing
 */
export function isShareable(entityName) {
    const config = getEntityConfig(entityName);
    return config?.shareable === true;
}
/**
 * Shareable entities configuration
 * Centralized list of entities that support shared URLs
 */
export const SHAREABLE_ENTITIES = {
    task: {
        name: 'task',
        displayName: 'Task',
        icon: 'CheckSquare',
        detailFields: ['name', 'descr', 'stage', 'priority_level', 'estimated_hours', 'actual_hours', 'story_points'],
        hasUpdates: true, // Shows task updates/comments
    },
    artifact: {
        name: 'artifact',
        displayName: 'Artifact',
        icon: 'FileText',
        detailFields: ['name', 'descr', 'artifact_type', 'file_format', 'file_size_bytes'],
        hasUpdates: false
    },
    wiki: {
        name: 'wiki',
        displayName: 'Wiki',
        icon: 'BookOpen',
        detailFields: ['name', 'descr'],
        hasUpdates: false,
        customRenderer: true, // Uses WikiContentRenderer
    },
    form: {
        name: 'form',
        displayName: 'Form',
        icon: 'FileText',
        detailFields: ['name', 'descr', 'form_schema'],
        hasUpdates: false,
        customRenderer: true, // Uses InteractiveForm
    }
};
